languages:
  Ruby: false
  JavaScript: true
  PHP: false
  Python: false
exclude_paths:
  - "libs/fuse.js"

engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 50